---
- name: Test playbook to check Ansible works
  hosts: all
  become: yes

  tasks:
    - name: Create a test file on each server
      ansible.builtin.file:
        path: /tmp/ansible_test_file
        state: touch

    - name: Show hostname of each server
      ansible.builtin.command: hostname
      register: host_output

    - name: Print hostname output
      ansible.builtin.debug:
        msg: "This is host: {{ host_output.stdout }}"
